import '@/plugins/fontawesome'
import '@/plugins/mixins'
import '@/plugins/oruga'
import '@/plugins/portal-vue'
// import '@/plugins/vue-api-query'
import '@/plugins/vue-chartkick'
import '@/plugins/vue-content-placeholders'
import '@/plugins/vue-dragscroll'
import '@/plugins/vue-multiselect'
import '@/plugins/vue-select'
import '@/plugins/vue-sidebar-menu'
import '@/plugins/vue-smart-table'
import '@/plugins/vue-tables-2'
import '@/plugins/vue-virtual-scroller'
import '@/plugins/vue2-frappe'
