import faker from 'faker'

const seedUsers = function (quantity, data) {
  for (let i = 1; i <= quantity; i++) {
    const gender = faker.random.number({min: 1, max: 2})
    const firstName = faker.name.firstName(gender)
    const lastName = faker.name.lastName(gender)

    data.users.push({
      id: i,
      name: faker.name.findName(firstName, lastName, gender),
      username: faker.internet.userName(firstName, lastName),
      email: faker.internet.email(firstName, lastName).toLowerCase(),
      gender,
      dateOfBirth: faker.date.past(55, new Date()),
      ocuppation: faker.name.jobTitle(),
      avatar: faker.internet.avatar(),
    })
  }
}

export const carriers = [
  {
    id: 1,
    name: 'Allstate',
    settings: {
      meta_title: 'Allstate Insurance Company',
      meta_desc: 'Volunteer Coordination System for Promise 686',
      color_primary: '#ABAC22',
      color_secondary: '#1F1D18',
      color_set_navbar: 'white-black',
      color_primary_text: '#fff',
      color_primary_contrast: 'offset',
      color_primary_offset: '#797a00',
      color_secondary_text: '#000',
      color_secondary_contrast: '',
      color_secondary_offset: '#514f4a',
    },
    status: 40,
    subdomain: null,
  },
]

export const categories = [
  {CategoryID: 1, CategoryName: 'Beverages'},
  {CategoryID: 2, CategoryName: 'Condiments'},
  {CategoryID: 3, CategoryName: 'Confections'},
  {CategoryID: 4, CategoryName: 'Dairy Products'},
  {CategoryID: 5, CategoryName: 'Grains/Cereals'},
  {CategoryID: 6, CategoryName: 'Meat/Poultry'},
  {CategoryID: 7, CategoryName: 'Produce'},
  {CategoryID: 8, CategoryName: 'Seafood'},
]

export const courseParticipants = [
  {
    id: 1,
    name: 'Victor Tolbert',
    imageUrl: '/assets/img/avatars/1.png',
    course: 'A Better Way to Learn',
    lastActivity: '2021-01-29 00:00:00',
    progress: 50,
  },
  {
    id: 2,
    name: 'Andy Cook',
    imageUrl: '/assets/img/avatars/2.png',
    course: 'Advocate Clinic Homework',
    lastActivity: '2021-01-28T13:30:00',
    progress: 50,
  },
  {
    id: 3,
    name: 'Patti Lytle',
    imageUrl: '/assets/img/avatars/3.png',
    course: 'Motivating and persuading',
    lastActivity: '2021-01-27T13:00:00',
    progress: 50,
  },
  {
    id: 4,
    name: 'Jeff Johnson',
    imageUrl: '/assets/img/avatars/4.png',
    course: 'Learning as you go',
    lastActivity: '2021-01-26T13:00:00',
    progress: 50,
  },
  {
    id: 5,
    name: 'Paul King',
    imageUrl: '/assets/img/avatars/5.png',
    course: 'The potential risks of advocacy',
    lastActivity: '2021-01-25T13:00:00',
    progress: 50,
  },
  {
    id: 6,
    name: 'Sammy Davis',
    imageUrl: '/assets/img/avatars/6.png',
    course: 'Good strategy requires great tactics',
    lastActivity: '2021-01-24T13:00:00',
    progress: 50,
  },
  {
    id: 7,
    name: 'Stepanie Fleet',
    imageUrl: '/assets/img/avatars/7.png',
    course: 'Motivating and persuading',
    lastActivity: '2021-01-23T13:00:00',
    progress: 50,
  },
  {
    id: 8,
    name: 'Eric Reese',

    imageUrl: '/assets/img/avatars/8.png',
    course: 'A Better Way to Learn',
    lastActivity: '2021-01-22T13:00:04',
    progress: 50,
  },
  {
    id: 9,
    name: 'Pam Oliver',
    imageUrl: '/assets/img/avatars/1.png',
    course: 'The potential risks of advocacy',
    lastActivity: '2021-01-21T13:00:00',
    progress: 50,
  },
  {
    id: 10,
    name: 'Jing Chen',
    imageUrl: '/assets/img/avatars/1.png',
    course: 'Good strategy requires great tactics',
    lastActivity: '2021-01-20T13:00:00',
    progress: 50,
  },
  {
    id: 11,
    name: 'Pamela James',
    imageUrl: '/assets/img/avatars/1.png',
    course: 'Learning as you go',
    lastActivity: '2021-01-14',
    progress: 50,
  },
  {
    id: 12,
    name: 'Jerome Tippins',
    imageUrl: '/assets/img/avatars/1.png',
    course: 'Motivating and persuading',
    lastActivity: '2021-01-14',
    progress: 50,
  },
  {
    id: 13,
    name: 'Craig Paulson',
    imageUrl: '/assets/img/avatars/1.png',
    course: 'Good strategy requires great tactics',
    lastActivity: '2021-01-04',
    progress: 50,
  },
  {
    id: 14,
    name: 'Seymore Butts',
    imageUrl: '/assets/img/avatars/1.png',
    course: 'All about Developmental Disablities',
    lastActivity: '2021-01-14',
    progress: 50,
  },
  {
    id: 15,
    name: 'Zeb Boston',
    imageUrl: '/assets/img/avatars/1.png',
    course: 'A Better Way to Learn',
    lastActivity: '2021-01-14',
    progress: 50,
  },
  {
    id: 16,
    name: 'Rebecca Gonzales',
    imageUrl: '/assets/img/avatars/1.png',
    course: 'Motivating and persuading',
    lastActivity: '2021-01-14',
    progress: 50,
  },
  {
    id: 17,
    name: 'Mike Jones',
    imageUrl: '/assets/img/avatars/1.png',
    course: 'All about Developmental Disablities',
    lastActivity: '2021-01-14',
    progress: 50,
  },
  {
    id: 18,
    name: 'Jeremy Doublestein',
    imageUrl: '/assets/img/avatars/1.png',
    course: 'All about Developmental Disablities',
    lastActivity: '2021-01-14',
    progress: 50,
  },
  {
    id: 19,
    name: 'Brent Stephens',
    imageUrl: '/assets/img/avatars/1.png',
    course: 'All about Developmental Disablities',
    lastActivity: '2021-01-14',
    progress: 50,
  },
  {
    id: 20,
    imageUrl: '/assets/img/avatars/1.png',
    name: 'Walter White',
    course: 'All about Developmental Disablities',
    lastActivity: '2021-01-14',
    progress: 50,
  },
  {
    id: 20,
    imageUrl: '/assets/img/avatars/1.png',
    name: 'Walter White',
    course: 'All about Developmental Disablities',
    lastActivity: '2021-01-14',
    progress: 50,
  },
  {
    id: 21,
    imageUrl: '/assets/img/avatars/1.png',
    name: 'Walter White',
    course: 'All about Developmental Disablities',
    lastActivity: '2021-01-14',
    progress: 50,
  },
]

export const movies = [
  {
    id: 1,
    user: {first_name: 'Jesse', last_name: 'Simmons'},
    date: '2016/10/15 13:43:27',
    gender: 'Male',
  },
  {
    id: 2,
    user: {first_name: 'John', last_name: 'Jacobs'},
    date: '2016/12/15 06:00:53',
    gender: 'Male',
  },
  {
    id: 3,
    user: {first_name: 'Tina', last_name: 'Gilbert'},
    date: '2016/04/26 06:26:28',
    gender: 'Female',
  },
  {
    id: 4,
    user: {first_name: 'Clarence', last_name: 'Flores'},
    date: '2016/04/10 10:28:46',
    gender: 'Male',
  },
  {
    id: 5,
    user: {first_name: 'Anne', last_name: 'Lee'},
    date: '2016/12/06 14:38:38',
    gender: 'Female',
  },
  {
    id: 6,
    user: {first_name: 'Sara', last_name: 'Armstrong'},
    date: '2016/09/23 18:50:04',
    gender: 'Female',
  },
  {
    id: 7,
    user: {first_name: 'Anthony', last_name: 'Webb'},
    date: '2016/08/30 23:49:38',
    gender: 'Male',
  },
  {
    id: 8,
    user: {first_name: 'Andrew', last_name: 'Greene'},
    date: '2016/11/20 14:57:47',
    gender: 'Male',
  },
  {
    id: 9,
    user: {first_name: 'Russell', last_name: 'White'},
    date: '2016/07/13 09:29:49',
    gender: 'Male',
  },
  {
    id: 10,
    user: {first_name: 'Lori', last_name: 'Hunter'},
    date: '2016/12/09 01:44:05',
    gender: 'Female',
  },
  {
    id: 11,
    user: {first_name: 'Ronald', last_name: 'Wood'},
    date: '2016/12/04 02:23:48',
    gender: 'Male',
  },
  {
    id: 12,
    user: {first_name: 'Michael', last_name: 'Harper'},
    date: '2016/07/27 13:28:15',
    gender: 'Male',
  },
  {
    id: 13,
    user: {first_name: 'George', last_name: 'Dunn'},
    date: '2017/03/07 12:26:52',
    gender: 'Male',
  },
  {
    id: 14,
    user: {first_name: 'Eric', last_name: 'Rogers'},
    date: '2016/06/07 05:41:52',
    gender: 'Male',
  },
  {
    id: 15,
    user: {first_name: 'Juan', last_name: 'Meyer'},
    date: '2017/02/01 04:56:34',
    gender: 'Male',
  },
  {
    id: 16,
    user: {first_name: 'Silvia', last_name: 'Rosa'},
    date: '2017/01/26 11:50:04',
    gender: 'Female',
  },
  {
    id: 17,
    user: {first_name: 'Lori', last_name: 'Cunningham'},
    date: '2016/05/01 10:00:56',
    gender: 'Female',
  },
  {
    id: 18,
    user: {first_name: 'Charles', last_name: 'Graham'},
    date: '2016/05/31 06:43:30',
    gender: 'Male',
  },
  {
    id: 19,
    user: {first_name: 'Henry', last_name: 'Morrison'},
    date: '2016/09/27 16:15:44',
    gender: 'Male',
  },
  {
    id: 20,
    user: {first_name: 'Albert', last_name: 'Mendoza'},
    date: '2016/08/08 05:29:24',
    gender: 'Male',
  },
  {
    id: 21,
    user: {first_name: 'Ruby', last_name: 'Snyder'},
    date: '2017/04/01 12:04:39',
    gender: 'Female',
  },
  {
    id: 22,
    user: {first_name: 'Jesse', last_name: 'Warren'},
    date: '2016/08/20 01:36:38',
    gender: 'Male',
  },
  {
    id: 23,
    user: {first_name: 'Carlos', last_name: 'Ferguson'},
    date: '2016/05/31 10:40:29',
    gender: 'Male',
  },
  {
    id: 24,
    user: {first_name: 'Melissa', last_name: 'Peters'},
    date: '2016/07/23 00:41:54',
    gender: 'Female',
  },
  {
    id: 25,
    user: {first_name: 'Arthur', last_name: 'Garza'},
    date: '2017/03/11 14:11:37',
    gender: 'Male',
  },
  {
    id: 26,
    user: {first_name: 'Joe', last_name: 'Berry'},
    date: '2016/07/09 15:16:56',
    gender: 'Male',
  },
  {
    id: 27,
    user: {first_name: 'Joseph', last_name: 'Bishop'},
    date: '2016/10/04 19:44:54',
    gender: 'Male',
  },
  {
    id: 28,
    user: {first_name: 'Sarah', last_name: 'Harper'},
    date: '2016/09/23 05:09:11',
    gender: 'Female',
  },
  {
    id: 29,
    user: {first_name: 'Christopher', last_name: 'Fuller'},
    date: '2016/04/12 00:05:35',
    gender: 'Male',
  },
  {
    id: 30,
    user: {first_name: 'Alan', last_name: 'Mendoza'},
    date: '2016/04/22 10:48:02',
    gender: 'Male',
  },
  {
    id: 31,
    user: {first_name: 'James', last_name: 'Davis'},
    date: '2017/01/16 15:17:03',
    gender: 'Male',
  },
  {
    id: 32,
    user: {first_name: 'Scott', last_name: 'Welch'},
    date: '2016/10/04 23:31:51',
    gender: 'Male',
  },
  {
    id: 33,
    user: {first_name: 'Mildred', last_name: 'Myers'},
    date: '2016/11/23 13:46:18',
    gender: 'Female',
  },
  {
    id: 34,
    user: {first_name: 'Victor', last_name: 'Martinez'},
    date: '2016/04/06 17:05:07',
    gender: 'Male',
  },
  {
    id: 35,
    user: {first_name: 'Susan', last_name: 'Medina'},
    date: '2016/12/09 10:33:37',
    gender: 'Female',
  },
  {
    id: 36,
    user: {first_name: 'Judy', last_name: 'Long'},
    date: '2016/07/26 16:19:04',
    gender: 'Female',
  },
  {
    id: 37,
    user: {first_name: 'Joan', last_name: 'Myers'},
    date: '2016/09/22 04:55:54',
    gender: 'Female',
  },
  {
    id: 38,
    user: {first_name: 'Rachel', last_name: 'Gonzales'},
    date: '2016/07/15 13:56:38',
    gender: 'Female',
  },
  {
    id: 39,
    user: {first_name: 'Roger', last_name: 'Hunt'},
    date: '2016/08/14 10:43:11',
    gender: 'Male',
  },
  {
    id: 40,
    user: {first_name: 'Dorothy', last_name: 'Howard'},
    date: '2016/06/19 05:34:49',
    gender: 'Female',
  },
  {
    id: 41,
    user: {first_name: 'Eugene', last_name: 'Lynch'},
    date: '2016/12/24 08:19:24',
    gender: 'Male',
  },
  {
    id: 42,
    user: {first_name: 'Kathy', last_name: 'Webb'},
    date: '2017/04/01 21:09:05',
    gender: 'Female',
  },
  {
    id: 43,
    user: {first_name: 'Antonio', last_name: 'White'},
    date: '2017/02/10 06:51:20',
    gender: 'Male',
  },
  {
    id: 44,
    user: {first_name: 'Louis', last_name: 'Spencer'},
    date: '2016/10/08 02:20:22',
    gender: 'Male',
  },
  {
    id: 45,
    user: {first_name: 'Andrea', last_name: 'Marshall'},
    date: '2016/09/04 10:59:57',
    gender: 'Female',
  },
  {
    id: 46,
    user: {first_name: 'Eugene', last_name: 'Sims'},
    date: '2017/03/15 06:39:48',
    gender: 'Male',
  },
  {
    id: 47,
    user: {first_name: 'Mildred', last_name: 'Gibson'},
    date: '2016/04/18 06:43:54',
    gender: 'Female',
  },
  {
    id: 48,
    user: {first_name: 'Joan', last_name: 'Arnold'},
    date: '2016/12/16 04:52:23',
    gender: 'Female',
  },
  {
    id: 49,
    user: {first_name: 'Jesse', last_name: 'Schmidt'},
    date: '2016/06/11 02:44:33',
    gender: 'Male',
  },
  {
    id: 50,
    user: {first_name: 'David', last_name: 'Frazier'},
    date: '2017/02/15 21:46:30',
    gender: 'Male',
  },
  {
    id: 51,
    user: {first_name: 'Nicholas', last_name: 'Howell'},
    date: '2016/11/01 15:08:31',
    gender: 'Male',
  },
  {
    id: 52,
    user: {first_name: 'Douglas', last_name: 'Chapman'},
    date: '2017/02/08 03:33:24',
    gender: 'Male',
  },
  {
    id: 53,
    user: {first_name: 'Bruce', last_name: 'Simmons'},
    date: '2016/07/14 12:11:17',
    gender: 'Male',
  },
  {
    id: 54,
    user: {first_name: 'Antonio', last_name: 'George'},
    date: '2016/11/07 19:12:55',
    gender: 'Male',
  },
  {
    id: 55,
    user: {first_name: 'Chris', last_name: 'Marshall'},
    date: '2016/07/03 12:11:45',
    gender: 'Male',
  },
  {
    id: 56,
    user: {first_name: 'Ashley', last_name: 'Hudson'},
    date: '2016/10/14 21:08:05',
    gender: 'Female',
  },
  {
    id: 57,
    user: {first_name: 'Alan', last_name: 'Edwards'},
    date: '2017/03/22 21:10:25',
    gender: 'Male',
  },
  {
    id: 58,
    user: {first_name: 'George', last_name: 'Clark'},
    date: '2016/04/28 03:15:05',
    gender: 'Male',
  },
  {
    id: 59,
    user: {first_name: 'Frank', last_name: 'Porter'},
    date: '2016/09/08 00:48:14',
    gender: 'Male',
  },
  {
    id: 60,
    user: {first_name: 'Christopher', last_name: 'Palmer'},
    date: '2016/05/24 08:58:12',
    gender: 'Male',
  },
]

export const products = [
  {
    ProductID: 1,
    ProductName: 'Tea',
    CategoryID: 1,
    QuantityPerUnit: '10 boxes x 20 bags',
    UnitPrice: 18.0,
    UnitsInStock: 39,
    Discontinued: false,
  },
  {
    ProductID: 7,
    ProductName: 'Dried Pears',
    CategoryID: 7,
    QuantityPerUnit: '12 - 1 lb pkgs.',
    UnitPrice: 30.0,
    UnitsInStock: 15,
    Discontinued: false,
  },
  {
    ProductID: 8,
    ProductName: 'Cranberry Sauce',
    CategoryID: 2,
    QuantityPerUnit: '12 - 12 oz jars',
    UnitPrice: 40.0,
    UnitsInStock: 6,
    Discontinued: false,
  },
  {
    ProductID: 9,
    ProductName: 'Mishi Kobe Niku',
    CategoryID: 6,
    QuantityPerUnit: '18 - 500 g pkgs.',
    UnitPrice: 97.0,
    UnitsInStock: 29,
    Discontinued: true,
  },
  {
    ProductID: 14,
    ProductName: 'Tofu',
    CategoryID: 7,
    QuantityPerUnit: '40 - 100 g pkgs.',
    UnitPrice: 23.25,
    UnitsInStock: 35,
    Discontinued: false,
  },
  {
    ProductID: 17,
    ProductName: 'Alice Mutton',
    CategoryID: 6,
    QuantityPerUnit: '20 - 1 kg tins',
    UnitPrice: 39.0,
    UnitsInStock: 0,
    Discontinued: false,
  },
  {
    ProductID: 19,
    ProductName: 'Teatime Biscuits',
    CategoryID: 3,
    QuantityPerUnit: '10 boxes x 12 pieces',
    UnitPrice: 9.2,
    UnitsInStock: 25,
    Discontinued: false,
  },
  {
    ProductID: 40,
    ProductName: 'Boston Crab Meat',
    CategoryID: 8,
    QuantityPerUnit: '24 - 4 oz tins',
    UnitPrice: 18.4,
    UnitsInStock: 123,
    Discontinued: false,
  },
  {
    ProductID: 43,
    ProductName: 'Coffee',
    CategoryID: 1,
    QuantityPerUnit: '16 - 500 g tins',
    UnitPrice: 46.0,
    UnitsInStock: 17,
    Discontinued: false,
  },
  {
    ProductID: 48,
    ProductName: 'Chocolate',
    CategoryID: 3,
    QuantityPerUnit: '10 pkgs.',
    UnitPrice: 12.75,
    UnitsInStock: 15,
    Discontinued: false,
  },
  {
    ProductID: 56,
    ProductName: 'Gnocchi di nonna Alice',
    CategoryID: 5,
    QuantityPerUnit: '24 - 250 g pkgs.',
    UnitPrice: 38.0,
    UnitsInStock: 21,
    Discontinued: true,
  },
  {
    ProductID: 57,
    ProductName: 'Ravioli Angelo',
    CategoryID: 5,
    QuantityPerUnit: '24 - 250 g pkgs.',
    UnitPrice: 19.5,
    UnitsInStock: 36,
    Discontinued: false,
  },
  {
    ProductID: 60,
    ProductName: 'Camembert Pierrot',
    CategoryID: 4,
    QuantityPerUnit: '15 - 300 g rounds',
    UnitPrice: 34.0,
    UnitsInStock: 19,
    Discontinued: true,
  },
  {
    ProductID: 65,
    ProductName: 'Hot Pepper Sauce',
    CategoryID: 2,
    QuantityPerUnit: '32 - 8 oz bottles',
    UnitPrice: 21.05,
    UnitsInStock: 76,
    Discontinued: false,
  },
  {
    ProductID: 72,
    ProductName: 'Mozzarella di Giovanni',
    CategoryID: 4,
    QuantityPerUnit: '24 - 200 g pkgs.',
    UnitPrice: 34.8,
    UnitsInStock: 14,
    Discontinued: false,
  },
  {
    ProductID: 73,
    ProductName: 'Röd Kaviar',
    CategoryID: 8,
    QuantityPerUnit: '24 - 150 g jars',
    UnitPrice: 15.0,
    UnitsInStock: 101,
    Discontinued: true,
  },
]

export const projects = [
  {
    id: 1,
    projectNumber: '190701010641',
    claimNumber: '123456',
    serviceTechnician: '',
    serviceType: 'Ladder Assist',
    city: 'Atlanta',
    state: 'GA',
    zip: '30316',
    region: 'Georgia',
    area: 'Atlanta',
    status: 'Assigned',
    flagged: '',
    date: '2021-06-21',
    start: '06:00',
    finish: '17:00',
    carrier: {
      name: '',
      adjuster: '',
    },
  },
]

export const projectStatuses = [
  {
    id: 1,
    name: 'Triage',
    count: 166,
  },
  {
    id: 2,
    name: 'Call Queue',
    count: 270,
  },
  {
    id: 3,
    name: 'Schedule',
    count: 1168,
  },
  {
    id: 4,
    name: 'Assigned',
    count: 1039,
  },
  {
    id: 5,
    name: 'Confirmed',
    count: 149,
  },
  {
    id: 6,
    name: 'Working',
    count: 74,
  },
  {
    id: 7,
    name: 'Review',
    count: 682,
  },
  {
    id: 8,
    name: 'Complete',
    count: 30,
  },
  {
    id: 9,
    name: 'Billed',
    count: 80,
  },
  {
    id: 10,
    name: 'Closed',
    count: 113967,
  },
  {
    id: 11,
    name: 'Hold',
    count: 250,
  },
  {
    id: 12,
    name: 'Archived',
    count: 166,
  },
  {
    id: 13,
    name: 'Pending',
    count: 251,
  },
]

export const roles = [
  {
    id: 1,
    name: 'Administrator',
    userTypeId: 1,
  },
  {
    id: 2,
    name: 'Scheduler',
    userTypeId: 1,
  },
  {
    id: 3,
    name: 'Admin Support',
    userTypeId: 1,
  },
  {
    id: 4,
    name: 'Bookkeeper',
    userTypeId: 1,
  },
  {
    id: 5,
    name: 'Service Tech',
    userTypeId: 2,
  },
  {
    id: 6,
    name: 'Service Tech 2',
    userTypeId: 2,
  },
  {
    id: 7,
    name: 'Service Manager',
    userTypeId: 2,
  },
  {
    id: 8,
    name: 'Insurance Adjuster',
    userTypeId: 3,
  },
  {
    id: 9,
    name: 'Billing Contact',
    userTypeId: 3,
  },
  {
    id: 10,
    name: 'Adjuster Director',
    userTypeId: 3,
  },
  {
    id: 11,
    name: 'Adjuster Manager',
    userTypeId: 3,
  },
  {
    id: 12,
    name: 'Service Director',
    userTypeId: 2,
  },
  {
    id: 13,
    name: 'EagleView',
    userTypeId: 4,
  },
]

export const serviceTypes = []

export const team = [
  {
    id: 1,
    name: 'Victor Tolbert',
    imageUrl: '/assets/img/avatars/1.png',
    course: 'A Better Way to Learn',
    lastActivity: '2021-01-29 00:00:00',
    progress: 50,
  },
  {
    id: 2,
    name: 'Andy Cook',
    imageUrl: '/assets/img/avatars/2.png',
    course: 'Advocate Clinic Homework',
    lastActivity: '2021-01-28T13:30:00',
    progress: 50,
  },
  {
    id: 3,
    name: 'Patti Lytle',
    imageUrl: '/assets/img/avatars/3.png',
    course: 'Motivating and persuading',
    lastActivity: '2021-01-27T13:00:00',
    progress: 50,
  },
  {
    id: 4,
    name: 'Jeff Johnson',
    imageUrl: '/assets/img/avatars/4.png',
    course: 'Learning as you go',
    lastActivity: '2021-01-26T13:00:00',
    progress: 50,
  },
  {
    id: 5,
    name: 'Paul King',
    imageUrl: '/assets/img/avatars/5.png',
    course: 'The potential risks of advocacy',
    lastActivity: '2021-01-25T13:00:00',
    progress: 50,
  },
  {
    id: 6,
    name: 'Sammy Davis',
    imageUrl: '/assets/img/avatars/6.png',
    course: 'Good strategy requires great tactics',
    lastActivity: '2021-01-24T13:00:00',
    progress: 50,
  },
  {
    id: 7,
    name: 'Stepanie Fleet',
    imageUrl: '/assets/img/avatars/7.png',
    course: 'Motivating and persuading',
    lastActivity: '2021-01-23T13:00:00',
    progress: 50,
  },
  {
    id: 8,
    name: 'Eric Reese',

    imageUrl: '/assets/img/avatars/8.png',
    course: 'A Better Way to Learn',
    lastActivity: '2021-01-22T13:00:04',
    progress: 50,
  },
  {
    id: 9,
    name: 'Pam Oliver',
    imageUrl: '/assets/img/avatars/1.png',
    course: 'The potential risks of advocacy',
    lastActivity: '2021-01-21T13:00:00',
    progress: 50,
  },
  {
    id: 10,
    name: 'Jing Chen',
    imageUrl: '/assets/img/avatars/1.png',
    course: 'Good strategy requires great tactics',
    lastActivity: '2021-01-20T13:00:00',
    progress: 50,
  },
  {
    id: 11,
    name: 'Pamela James',
    imageUrl: '/assets/img/avatars/1.png',
    course: 'Learning as you go',
    lastActivity: '2021-01-14',
    progress: 50,
  },
  {
    id: 12,
    name: 'Jerome Tippins',
    imageUrl: '/assets/img/avatars/1.png',
    course: 'Motivating and persuading',
    lastActivity: '2021-01-14',
    progress: 50,
  },
  {
    id: 13,
    name: 'Craig Paulson',
    imageUrl: '/assets/img/avatars/1.png',
    course: 'Good strategy requires great tactics',
    lastActivity: '2021-01-04',
    progress: 50,
  },
  {
    id: 14,
    name: 'Seymore Butts',
    imageUrl: '/assets/img/avatars/1.png',
    course: 'All about Developmental Disablities',
    lastActivity: '2021-01-14',
    progress: 50,
  },
  {
    id: 15,
    name: 'Zeb Boston',
    imageUrl: '/assets/img/avatars/1.png',
    course: 'A Better Way to Learn',
    lastActivity: '2021-01-14',
    progress: 50,
  },
  {
    id: 16,
    name: 'Rebecca Gonzales',
    imageUrl: '/assets/img/avatars/1.png',
    course: 'Motivating and persuading',
    lastActivity: '2021-01-14',
    progress: 50,
  },
  {
    id: 17,
    name: 'Mike Jones',
    imageUrl: '/assets/img/avatars/1.png',
    course: 'All about Developmental Disablities',
    lastActivity: '2021-01-14',
    progress: 50,
  },
  {
    id: 18,
    name: 'Jeremy Doublestein',
    imageUrl: '/assets/img/avatars/1.png',
    course: 'All about Developmental Disablities',
    lastActivity: '2021-01-14',
    progress: 50,
  },
  {
    id: 19,
    name: 'Brent Stephens',
    imageUrl: '/assets/img/avatars/1.png',
    course: 'All about Developmental Disablities',
    lastActivity: '2021-01-14',
    progress: 50,
  },
  {
    id: 20,
    imageUrl: '/assets/img/avatars/1.png',
    name: 'Walter White',
    course: 'All about Developmental Disablities',
    lastActivity: '2021-01-14',
    progress: 50,
  },
  {
    id: 20,
    imageUrl: '/assets/img/avatars/1.png',
    name: 'Walter White',
    course: 'All about Developmental Disablities',
    lastActivity: '2021-01-14',
    progress: 50,
  },
  {
    id: 21,
    imageUrl: '/assets/img/avatars/1.png',
    name: 'Walter White',
    course: 'All about Developmental Disablities',
    lastActivity: '2021-01-14',
    progress: 50,
  },
]

export const users = [
  {
    id: 1,
    user: {first_name: 'Jesse', last_name: 'Simmons'},
    date: '2016/10/15 13:43:27',
    gender: 'Male',
  },
]

export const userTypes2 = [
  {name: 'Administrator'},
  {name: 'Insurance Adjuster'},
  {name: 'Customer Service Representative'},
  {name: 'Claims Representative'},
  {name: 'Field Technician'},
  {name: 'Carrier Staff'},
  {name: 'Super User'},
]

export const userTypes3 = [
  {id: 1, name: 'Application Users'},
  {id: 2, name: 'Service Technicians'},
  {id: 3, name: 'Insurance Adjusters'},
  {id: 4, name: 'WebAPI Users'},
]

export const userTypes = [
  {
    Id: 1,
    Name: 'Application Users',
  },
  {
    Id: 2,
    Name: 'Service Technicians',
  },
  {
    Id: 3,
    Name: 'Insurance Adjusters',
  },
  {
    Id: 4,
    Name: 'WebAPI Users',
  },
]

const db = function () {
  const data = {
    users: [],
  }

  seedUsers(100, data)

  return data
}

export default db
