DROP TABLE [dbo].[User];
-- This script only contains the table creation statements and does not fully represent the table in the database. It's still missing: sequences, indices, triggers. Do not use it as a backup.

CREATE TABLE [dbo].[User] (
    [Id] int,
    [AddressLatitude] float,
    [AddressLongitude] float,
    [Comment] varchar,
    [CreatedBy] int,
    [CreatedOn] datetime DEFAULT (getdate()),
    [DeactivationDate] datetime DEFAULT (getdate()),
    [FirstName] varchar,
    [HaagCertificationNumber] varchar,
    [Initials] varchar,
    [IsActive] bit DEFAULT ((0)),
    [IsApproved] bit DEFAULT ((0)),
    [IsHaagCertified] bit DEFAULT ((0)),
    [IsInCollections] bit DEFAULT ((0)),
    [LastLogin] datetime DEFAULT (getdate()),
    [LastName] varchar,
    [MailingCity] varchar,
    [MailingPostalCode] varchar,
    [MailingStateId] int,
    [MailingStreetAddress1] varchar,
    [MailingStreetAddress2] varchar,
    [MiddleName] varchar,
    [PrimaryEmail] varchar,
    [PrimaryPhone] varchar,
    [PrimaryPhoneExt] varchar,
    [RoleId] int,
    [SecondaryEmail] varchar,
    [SecondaryPhone] varchar,
    [ServiceCity] varchar,
    [ServicePostalCode] varchar,
    [ServiceStateId] int,
    [ServiceStreetAddress1] varchar,
    [ServiceStreetAddress2] varchar,
    [SmsEmail] varchar,
    [UserTypeId] int,
    [RowVersion] timestamp,
    CONSTRAINT [FK_User_State_MailingStateId] FOREIGN KEY ([MailingStateId]) REFERENCES [dbo].[State]([Id]),
    CONSTRAINT [FK_User_Role_RoleId] FOREIGN KEY ([RoleId]) REFERENCES [dbo].[Role]([Id]),
    CONSTRAINT [FK_User_State_ServiceStateId] FOREIGN KEY ([ServiceStateId]) REFERENCES [dbo].[State]([Id]),
    CONSTRAINT [FK_User_UserType_UserTypeId] FOREIGN KEY ([UserTypeId]) REFERENCES [dbo].[UserType]([Id]),
    PRIMARY KEY ([Id])
);

